./GetData.sh category3.csv
./GetData.sh category4.csv
./GetData.sh category5.csv
./GetData.sh category6.csv
./GetData.sh category7.csv
./GetData.sh category8.csv
./GetData.sh category9.csv
./GetData.sh category10.csv
./GetData.sh category11.csv
./GetData.sh category12.csv
./GetData.sh category13.csv
./GetData.sh category14.csv
./GetData.sh category15.csv
./GetData.sh category16.csv
./GetData.sh category17.csv
./GetData.sh category18.csv
./GetData.sh category19.csv
./GetData.sh category20.csv
./GetData.sh category21.csv
./GetData.sh category22.csv
./GetData.sh category23.csv
./GetData.sh category24.csv
./GetData.sh category25.csv
./GetData.sh category26.csv
./GetData.sh category27.csv
./GetData.sh category28.csv
./GetData.sh category29.csv
./GetData.sh category30.csv
./GetData.sh category31.csv
./GetData.sh category32.csv
./GetData.sh category33.csv
./GetData.sh category34.csv
./GetData.sh category35.csv